
GET  http://localhost:5185/

###
GET  http://localhost:5185/api/categories
###
# GET  http://localhost:5185/api/categories?searchProducts=Nusrat
# ###

POST  http://localhost:5185/api/categories
Content-Type: application/json

{
"name":"Tuba",
"description":" Good Human"
}
###

PUT  http://localhost:5185/api/categories/214066e8-0407-44c4-a00e-35aac8b3fc0d
Content-Type: application/json

{
"name":"Jhakir",
"description":"is man is normal"
}
###

DELETE http://localhost:5185/api/categories/5fbbc70b-8f69-4c1c-aca6-a0253ffdd7e7
###

