
GET  http://localhost:5185/

###
GET  http://localhost:5185/api/categories
###
# GET  http://localhost:5185/api/categories?searchProducts=Nusrat
# ###

POST  http://localhost:5185/api/categories
Content-Type: application/json

{
"name":"kawsar",
"description":" Bad Categiry"

}
# {
# "name":"Md.Kawsar",
# "description":"My First Project in Dotnet Core!"
# }
###



PUT  http://localhost:5185/api/categories/9f661f08-8567-4b23-8301-e3d9556366a1
Content-Type: application/json

{
"name":"Ug",
"description":""
}
###

DELETE http://localhost:5185/api/categories/5fbbc70b-8f69-4c1c-aca6-a0253ffdd7e7
###

